DustTournamentKeeper/ViewModels/FactionViewModel.cs
using DustTournamentKeeper.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace DustTournamentKeeper.ViewModels
{
    public class FactionViewModel
    {
        public int Id { get; set; }
        public int? GameId { get; set; }
        public int? BlockId { get; set; }
        public string Name { get; set; }
        public string Slogan { get; set; }
        public string Logo { get; set; }
        public string Icon { get; set; }

        public List<SelectListItem> GamesAvailable { get; set; } = new List<SelectListItem>();
        public List<SelectListItem> BlocksAvailable { get; set; } = new List<SelectListItem>();

        public FactionViewModel()
        {

        }

        public FactionViewModel(Faction faction)
        {
            Id = faction.Id;
            GameId = faction.GameId;
            BlockId = faction.BlockId;
            Name = faction.Name;
            Slogan = faction.Slogan;
            Logo = faction.Logo;
            Icon = faction.Icon;
        }
    }
}

DustTournamentKeeper/Controllers/FactionController.cs
using DustTournamentKeeper.Infrastructure;
using DustTournamentKeeper.Models;
using DustTournamentKeeper.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DustTournamentKeeper.Controllers
{
    [Authorize(Roles = nameof(Roles.Administrator))]
    public class FactionController : Controller
    {
        private readonly ITournamentRepository _repository;

        public FactionController(ITournamentRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index() => View(_repository.Factions
            .Include(f => f.Game)
            .Include(f => f.Block)
            .ToList());

        public IActionResult Upsert(int? id)
        {
            var factionViewModel = id.HasValue
                ? new FactionViewModel(_repository.Factions
                .Include(f => f.Game)
                .Include(f => f.Block)
                .FirstOrDefault(f => f.Id == id.Value))
                : new FactionViewModel();
            PrepareViewModel(factionViewModel);

            return View(factionViewModel);
        }

        [HttpPost]
        public IActionResult Upsert(FactionViewModel factionViewModel)
        {
            if (!ModelState.IsValid)
            {
                PrepareViewModel(factionViewModel);
                return View(factionViewModel);
            }

            var faction = new Faction
            {
                Id = factionViewModel.Id > 0 ? factionViewModel.Id : 0,
                Name = factionViewModel.Name,
                Slogan = factionViewModel.Slogan,
                Logo = factionViewModel.Logo,
                Icon = factionViewModel.Icon,
                GameId = factionViewModel.GameId,
                BlockId = factionViewModel.BlockId
            };

            if (faction.Id > 0)
            {
                var oldFaction = _repository.Factions.FirstOrDefault(b => b.Id == faction.Id);
                _repository.Update(oldFaction, faction);
            }
            else
            {
                _repository.Add(faction);
            }

            return RedirectToAction(nameof(FactionController.Details), new { id = faction.Id });
        }

        private void PrepareViewModel(FactionViewModel factionViewModel)
        {
            factionViewModel.GamesAvailable = _repository.Games.Select(g => new SelectListItem
            {
                Text = g.Name,
                Value = g.Id.ToString()
            }).ToList();

            factionViewModel.BlocksAvailable = _repository.Blocks.Select(b => new SelectListItem
            {
                Text = b.Name,
                Value = b.Id.ToString()
            }).ToList();
        }

        public IActionResult Details(int id)
        {
            var faction = _repository.Factions
                .Include(f => f.Game)
                .Include(f => f.Block)
                .FirstOrDefault(f => f.Id == id);

            if (faction == null)
            {
                return NotFound();
            }

            return View(faction);
        }

        public IActionResult Remove(int id)
        {
            var faction = _repository.Factions.FirstOrDefault(f => f.Id == id);

            if (faction == null)
            {
                return NotFound();
            }

            _repository.Delete(faction);

            return RedirectToAction(nameof(FactionController.Index));
        }

        [HttpPost]
        public async Task<ActionResult<List<Faction>>> GetAvailableFactions(int blockId)
        {
            if (blockId == 0)
            {
                return new List<Faction>();
            }

            var factions = await _repository.Factions.Where(f => f.BlockId == blockId).ToListAsync();

            if (factions == null)
            {
                return NotFound();
            }

            return factions;
        }
    }
}

DustTournamentKeeper/Views/Faction/Details.cshtml
@model Faction

@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = @Localizer["FactionDetails"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<a class="btn btn-secondary mb-1" asp-controller="Faction" asp-action="Upsert" asp-route-id="@Model.Id">@Localizer["Edit"]</a>
<a class="btn btn-secondary mb-1" asp-controller="Faction" asp-action="Index">@Localizer["List"]</a><br />
<div class="container">
    <div class="row">
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Localizer["Name"]</p></div>
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Model.Name</p></div>
    </div>
    <div class="row">
        <div class="col-md-4"><p>@Localizer["Game"]</p></div>
        <div class="col-md-4"><a class="alert-link" asp-controller="Game" asp-action="Details" asp-route-id="@Model.GameId">@Model.Game?.Name</a></div>
    </div>
    <div class="row">
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Localizer["Block"]</p></div>
        <div class="col-md-4 border border-secondary bg-secondary"><a class="alert-link text-black-50" asp-controller="Block" asp-action="Details" asp-route-id="@Model.BlockId">@Model.Block?.Name</a></div>
    </div>
    <div class="row">
        <div class="col-md-4"><p>@Localizer["Slogan"]</p></div>
        <div class="col-md-4"><p>@Model.Slogan</p></div>
    </div>
    @if (Model.Logo != null)
    {
        <div class="row">
            <div class="col-md-4"><p>@Localizer["Logo"]</p></div>
            <div class="col-md-4"><img src="@Model.Logo" alt="@Model.Name" /></div>
        </div>
    }
    @if (Model.Icon != null)
    {
        <div class="row">
            <div class="col-md-4"><p>@Localizer["Icon"]</p></div>
            <div class="col-md-4"><img src="@Model.Icon" alt="@Model.Name" /></div>
        </div>
    }
</div>

DustTournamentKeeper/Views/Faction/Index.cshtml
@model IEnumerable<Faction>

@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["FactionsTitle"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Localizer["Factions"]</h2>
<a class="btn btn-secondary mb-1" asp-controller="Faction" asp-action="Upsert">@Localizer["Create"]</a>

<table class="table table-striped table-dark table-hover table-sm table-responsive-sm">
    <thead>
        <tr>
            <th scope="col">@Localizer["Name"]</th>
            <th scope="col">@Localizer["Game"]</th>
            <th scope="col">@Localizer["Block"]</th>
            <th scope="col">@Localizer["Slogan"]</th>
            <th scope="col">@Localizer["Logo"]</th>
            <th scope="col">@Localizer["Icon"]</th>
            <th scope="col">@Localizer["Action"]</th>
        </tr>
    </thead>
    <tbody>
        @if (Model == null || Model.Count() == 0)
        {
            <tr><td colspan="4">@Localizer["NoFactions"]</td></tr>
        }
        else
        {
            @foreach (var faction in Model)
            {
            <tr>
                <th scope="row"><a asp-controller="Faction" asp-action="Details" asp-route-id="@faction.Id">@faction.Name</a></th>
                <td><a asp-controller="Game" asp-action="Details" asp-route-id="@faction.Game?.Id">@faction.Game?.Name</a></td>
                <td><a asp-controller="Block" asp-action="Details" asp-route-id="@faction.Block?.Id">@faction.Block?.Name</a></td>
                <td>@faction.Slogan</td>
                <td>
                    @if (faction.Logo != null)
                    {<img src="@faction.Logo" alt="@faction.Name" />}
                </td>
                <td>
                    @if (faction.Icon != null)
                    {<img src="@faction.Icon" alt="@faction.Name" />}
                </td>
                <td><a asp-controller="Faction" asp-action="Remove" asp-route-id="@faction.Id">@Localizer["Remove"]</a></td>
            </tr>
            }
        }
    </tbody>
</table>

DustTournamentKeeper/Views/Faction/Upsert.cshtml
@model FactionViewModel

@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["UpsertFaction"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/js/RestUtility.js"></script>

<h2>@(Model.Id > 0 ? Localizer["EditFaction"] : Localizer["CreateFaction"])</h2>

<form asp-controller="Faction" asp-action="Upsert" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label>@Localizer["Name"]</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label>@Localizer["Game"]</label>
        <select id="gameSelect" asp-for="GameId" asp-items="@Model.GamesAvailable" class="form-control btn btn-secondary">
            <option value="@null">@Localizer["PleaseSelect"]</option>
        </select>
        <span asp-validation-for="GameId"></span>
    </div>

    <div class="form-group">
        <label>@Localizer["Block"]</label>
        <select id="blockSelect" asp-for="BlockId" asp-items="@Model.BlocksAvailable" class="form-control btn btn-secondary">
            <option value="@null">@Localizer["PleaseSelect"]</option>
        </select>
        <span asp-validation-for="BlockId"></span>
    </div>

    <div class="form-group">
        <label>@Localizer["Slogan"]</label>
        <input asp-for="Slogan" class="form-control" />
        <span asp-validation-for="Slogan"></span>
    </div>

    <div class="input-group form-group">
        <div class="input-group-prepend">
            <span class="input-group-text" id="uploadLogoFileLabel">@Localizer["UploadLogo"]</span>
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="uploadLogoFile"
                   aria-describedby="uploadLogoFileLabel">
            <label class="custom-file-label" for="inputGroupFile01">@Localizer["ChooseFile"]</label>
        </div>
    </div>

    <div class="input-group form-group">
        <div class="input-group-prepend">
            <span class="input-group-text" id="uploadIconFileLabel">@Localizer["UploadIcon"]</span>
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="uploadIconFile"
                   aria-describedby="uploadIconFileLabel">
            <label class="custom-file-label" for="inputGroupFile01">@Localizer["ChooseFile"]</label>
        </div>
    </div>

    <div class="text-center">
        <input class="btn btn-secondary" type="submit" value="@Localizer["Save"]" />
        <a class="btn btn-secondary" asp-controller="Faction" asp-action="Index">@Localizer["Discard"]</a>
    </div>
</form>

<script>
    $(document).ready(function () {
        $('#gameSelect').change(getAvailableBlocks);
    });
</script>