DustTournamentKeeper/Models/Game.cs
using System.Collections.Generic;

namespace DustTournamentKeeper.Models
{
    public partial class Game
    {
        public Game()
        {
            Blocks = new List<Block>();
            Factions = new List<Faction>();
            Tournaments = new List<Tournament>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string Icon { get; set; }
        public string Slogan { get; set; }
        public string Description { get; set; }

        public virtual IList<Block> Blocks { get; set; }
        public virtual IList<Faction> Factions { get; set; }
        public virtual IList<Tournament> Tournaments { get; set; }
    }
}

DustTournamentKeeper/Controllers/GameController.cs
using DustTournamentKeeper.Infrastructure;
using DustTournamentKeeper.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DustTournamentKeeper.Controllers
{
    [Authorize(Roles = nameof(Roles.Administrator))]
    public class GameController : Controller
    {
        private readonly ITournamentRepository _repository;

        public GameController(ITournamentRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index() => View(_repository.Games.ToList());

        public IActionResult Upsert(int? id)
        {
            var game = id.HasValue ? _repository.Games.FirstOrDefault(g => g.Id == id.Value) : new Game();
            return View(game);
        }

        [HttpPost]
        public IActionResult Upsert(Game game)
        {
            if (!ModelState.IsValid)
            {
                return View(game);
            }

            if (game.Id > 0)
            {
                var oldGame = _repository.Games.FirstOrDefault(g => g.Id == game.Id);
                _repository.Update(oldGame, game);
            }
            else
            {
                _repository.Add(game);
            }

            return RedirectToAction(nameof(GameController.Details), new { id = game.Id });
        }

        public IActionResult Details(int id)
        {
            var game = _repository.Games.FirstOrDefault(g => g.Id == id);

            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        public IActionResult Remove(int id)
        {
            var game = _repository.Games.FirstOrDefault(g => g.Id == id);

            if (game == null)
            {
                return NotFound();
            }

            _repository.Delete(game);

            return RedirectToAction(nameof(GameController.Index));
        }
    }
}

DustTournamentKeeper/Views/Game/Details.cshtml
@model Game

@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = @Localizer["GameDetails"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<a class="btn btn-secondary mb-1" asp-controller="Game" asp-action="Upsert" asp-route-id="@Model.Id">@Localizer["Edit"]</a>
<a class="btn btn-secondary mb-1" asp-controller="Game" asp-action="Index">@Localizer["List"]</a>
<br />
<div class="container">
    <div class="row">
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Localizer["Name"]</p></div>
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Model.Name</p></div>
    </div>
    <div class="row">
        <div class="col-md-4"><p>@Localizer["Slogan"]</p></div>
        <div class="col-md-4"><p>@Model.Slogan</p></div>
    </div>
    <div class="row">
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Localizer["Description"]</p></div>
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Model.Description</p></div>
    </div>
    @if (Model.Logo != null)
    {
        <div class="row">
            <div class="col-md-4"><p>@Localizer["Logo"]</p></div>
            <div class="col-md-4"><img src="@Model.Logo" alt="@Model.Name" /></div>
        </div>
    }
    @if (Model.Icon != null)
    {
        <div class="row">
            <div class="col-md-4"><p>@Localizer["Icon"]</p></div>
            <div class="col-md-4"><img src="@Model.Icon" alt="@Model.Name" /></div>
        </div>
    }
</div>

DustTournamentKeeper/Views/Game/Index.cshtml
@model IEnumerable<Game>

@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["GamesTitle"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Localizer["Games"]</h2>
<a class="btn btn-secondary mb-1" asp-controller="Game" asp-action="Upsert">@Localizer["Create"]</a>

<table class="table table-striped table-dark table-hover table-sm table-responsive-sm">
    <thead>
        <tr>
            <th scope="col">@Localizer["Name"]</th>
            <th scope="col">@Localizer["Slogan"]</th>
            <th scope="col">@Localizer["Description"]</th>
            <th scope="col">@Localizer["Logo"]</th>
            <th scope="col">@Localizer["Icon"]</th>
            <th scope="col">@Localizer["Action"]</th>
        </tr>
    </thead>
    <tbody>
        @if (Model == null || Model.Count() == 0)
        {
            <tr><td colspan="4">@Localizer["NoGames"]</td></tr>
        }
        else
        {
            @foreach (var game in Model)
            {
            <tr>
                <th scope="row"><a asp-controller="Game" asp-action="Details" asp-route-id="@game.Id">@game.Name</a></th>
                <td>@game.Slogan</td>
                <td>@game.Description</td>
                <td>@if (game.Logo != null)
                {<img src="@game.Logo" alt="@game.Name" />}</td>
                <td>@if (game.Icon != null)
                {<img src="@game.Icon" alt="@game.Name" />}</td>
                <td><a asp-controller="Game" asp-action="Remove" asp-route-id="@game.Id">@Localizer["Remove"]</a></td>
            </tr>
            }
        }
    </tbody>
</table>

DustTournamentKeeper/Views/Game/Upsert.cshtml
@model Game

@inject  IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["UpsertGame"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@(Model.Id > 0 ? Localizer["EditGame"] : Localizer["CreateGame"])</h2>

<form asp-controller="Game" asp-action="Upsert" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label>@Localizer["Name"]</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label>@Localizer["Slogan"]</label>
        <input asp-for="Slogan" class="form-control" />
        <span asp-validation-for="Slogan"></span>
    </div>

    <div class="form-group">
        <label>@Localizer["Description"]</label>
        <input asp-for="Description" class="form-control" />
        <span asp-validation-for="Description"></span>
    </div>

    <div class="input-group form-group">
        <div class="input-group-prepend">
            <span class="input-group-text" id="uploadLogoFileLabel">@Localizer["UploadLogo"]</span>
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="uploadLogoFile"
                   aria-describedby="uploadLogoFileLabel">
            <label class="custom-file-label" for="inputGroupFile01">@Localizer["ChooseFile"]</label>
        </div>
    </div>

    <div class="input-group form-group">
        <div class="input-group-prepend">
            <span class="input-group-text" id="uploadIconFileLabel">@Localizer["UploadIcon"]</span>
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="uploadIconFile"
                   aria-describedby="uploadIconFileLabel">
            <label class="custom-file-label" for="inputGroupFile01">@Localizer["ChooseFile"]</label>
        </div>
    </div>

    <div class="text-center">
        <input class="btn btn-secondary" type="submit" value="@Localizer["Save"]" />
        <a class="btn btn-secondary" asp-controller="Game" asp-action="Index">@Localizer["Discard"]</a>
    </div>
</form>