DustTournamentKeeper/Controllers/ManagementController.cs
using DustTournamentKeeper.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DustTournamentKeeper.Controllers
{
    [Authorize(Roles = nameof(Roles.Administrator))]
    public class ManagementController : Controller
    {
        public IActionResult Index() => View();

        public IActionResult HowTo() => View();
    }
}

DustTournamentKeeper/Views/Management/HowTo.cshtml
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["HowToTitle"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Localizer["HowToSubtitle"]</h1>
<ol>
    <li><strong>Draft</strong> - @Localizer["Draft"]</li>
    <li><strong>Pending</strong> - @Localizer["Pending"]</li>
    <li><strong>Ongoing</strong> - @Localizer["Ongoing"]</li>
    <li><strong>Finished</strong> - @Localizer["Finished"]</li>
    <li><strong>Cancelled</strong> - @Localizer["Cancelled"]</li>
</ol>

DustTournamentKeeper/Views/Management/Index.cshtml
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["ManagementTitle"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="container">
    <div class="row">
        <div class="col-md-5"><a class="btn btn-secondary mb-1" asp-controller="Game" asp-action="Index">@Localizer["Games"]</a></div>
        <div class="col-md-5"><a class="btn btn-secondary mb-1" asp-controller="Block" asp-action="Index">@Localizer["Blocks"]</a></div>
        <div class="col-md-5"><a class="btn btn-secondary mb-1" asp-controller="Faction" asp-action="Index">@Localizer["Factions"]</a></div>
        <div class="col-md-5"><a class="btn btn-secondary mb-1" asp-controller="BoardType" asp-action="Index">@Localizer["BoardTypes"]</a></div>
        <div class="col-md-5"><a class="btn btn-secondary mb-1" asp-controller="Players" asp-action="AdminIndex">@Localizer["Players"]</a></div>
        <div class="col-md-5"><a class="btn btn-secondary mb-1" asp-controller="Management" asp-action="HowTo">@Localizer["HowTo"]</a></div>
    </div>
</div>