DustTournamentKeeper/Models/Club.cs
using System.Collections.Generic;

namespace DustTournamentKeeper.Models
{
    public class Club
    {
        public Club()
        {
            Tournaments = new List<Tournament>();
            Users = new List<User>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Logo { get; set; }
        public string Icon { get; set; }
        public string Slogan { get; set; }
        public string Address { get; set; }

        public virtual IList<Tournament> Tournaments { get; set; }
        public virtual IList<User> Users { get; set; }
    }
}

DustTournamentKeeper/Controllers/ClubsController.cs
using DustTournamentKeeper.Infrastructure;
using DustTournamentKeeper.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DustTournamentKeeper.Controllers
{
    public class ClubsController : Controller
    {
        private readonly ITournamentRepository _repository;

        public ClubsController(ITournamentRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View(_repository.Clubs.ToList());
        }

        public IActionResult Details(int id)
        {
            var club = _repository.Clubs.FirstOrDefault(c => c.Id == id);

            if (club == null)
            {
                return NotFound();
            }

            return View(club);
        }

        [Authorize]
        public IActionResult Upsert(int? id)
        {
            var club = id.HasValue ? _repository.Clubs.FirstOrDefault(c => c.Id == id.Value) : new Club();

            return View(club);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Upsert(Club club)
        {
            if (club.Id < 1)
            {
                _repository.Add(club);
            }
            else
            {
                var oldCLub = _repository.Clubs.FirstOrDefault(c => c.Id == club.Id);
                if (oldCLub == null)
                {
                    return NotFound();
                }

                _repository.Update(oldCLub, club);
            }

            return RedirectToAction("Details", new { id = club.Id });
        }

        [Authorize(Roles = nameof(Roles.Administrator))]
        public IActionResult Remove(int id)
        {
            var club = _repository.Clubs.FirstOrDefault(c => c.Id == id);

            if (club == null)
            {
                return NotFound();
            }

            _repository.Delete(club);

            return RedirectToAction(nameof(ClubsController.Index));
        }
    }
}

DustTournamentKeeper/Views/Clubs/Details.cshtml
@model Club

@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = @Localizer["ClubDetails"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<a class="btn btn-secondary mb-1" asp-controller="Clubs" asp-action="Upsert" asp-route-id="@Model.Id">@Localizer["Edit"]</a>
<a class="btn btn-secondary mb-1" asp-controller="Clubs" asp-action="Remove" asp-route-id="@Model.Id">@Localizer["Delete"]</a>
<a class="btn btn-secondary mb-1" asp-controller="Clubs" asp-action="Index">@Localizer["List"]</a>
<br />
<div class="container">
    <div class="row">
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Localizer["Name"]</p></div>
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Model.Name</p></div>
    </div>
    <div class="row">
        <div class="col-md-4"><p>@Localizer["City"]</p></div>
        <div class="col-md-4"><p>@Model.City</p></div>
    </div>
    <div class="row">
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Localizer["Address"]</p></div>
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Model.Address</p></div>
    </div>
    <div class="row">
        <div class="col-md-4"><p>@Localizer["Slogan"]</p></div>
        <div class="col-md-4"><p>@Model.Slogan</p></div>
    </div>
    <div class="row">
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Localizer["City"]</p></div>
        <div class="col-md-4 border border-secondary bg-secondary"><p>@Model.City</p></div>
    </div>
    @if (!string.IsNullOrEmpty(Model.Logo))
    {
        <div class="row">
            <div class="col-md-4"><p>@Localizer["Logo"]</p></div>
            <div class="col-md-4"><img src="@Model.Logo" alt="@Model.Name" /></div>
        </div>
    }
</div>

DustTournamentKeeper/Views/Clubs/Index.cshtml
@model IEnumerable<Club>

@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["ClubsTitle"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Localizer["Clubs"]</h2>
<a class="btn btn-secondary mb-1" asp-controller="Clubs" asp-action="Upsert">@Localizer["Create"]</a>

<table class="table table-striped table-dark table-hover table-sm table-responsive-sm">
    <thead>
        <tr>
            <th scope="col">@Localizer["Name"]</th>
            <th scope="col">@Localizer["City"]</th>
            <th scope="col">@Localizer["Address"]</th>
            <th scope="col">@Localizer["Slogan"]</th>
        </tr>
    </thead>
    <tbody>
        @if (Model == null || Model.Count() == 0)
        {
            <tr><td colspan="4">@Localizer["NoClubs"]</td></tr>
        }
        else
        {
            @foreach (var club in Model)
            {
            <tr>
                <th scope="row"><a asp-controller="Clubs" asp-action="Details" asp-route-id="@club.Id">@club.Name</a></th>
                <td>@club.City</td>
                <td>@club.Address</td>
                <td>@club.Slogan</td>
            </tr>
            }
        }
    </tbody>
</table>

DustTournamentKeeper/Views/Clubs/Upsert.cshtml
@model Club

@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["UpsertClub"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@(Model.Id > 0 ? Localizer["EditClub"] : Localizer["CreateClub"])</h2>

<form asp-action="Upsert" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label>@Localizer["Name"]</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label>@Localizer["Country"]</label>
        <input asp-for="Country" class="form-control" />
        <span asp-validation-for="Country"></span>
    </div>

    <div class="form-group">
        <label>@Localizer["City"]</label>
        <input asp-for="City" class="form-control" />
        <span asp-validation-for="City"></span>
    </div>

    <div class="form-group">
        <label>@Localizer["Address"]</label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address"></span>
    </div>

    <div class="form-group">
        <label>@Localizer["Slogan"]</label>
        <input asp-for="Slogan" class="form-control" />
        <span asp-validation-for="Slogan"></span>
    </div>

    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text" id="uploadLogoFileLabel">@Localizer["Upload"]</span>
        </div>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="uploadLogoFile"
                   aria-describedby="uploadLogoFileLabel">
            <label class="custom-file-label" for="inputGroupFile01">@Localizer["ChooseFile"]</label>
        </div>
    </div>

    <div class="text-center">
        <input class="btn btn-secondary" type="submit" value="@Localizer["Save"]" />
        <a class="btn btn-secondary" asp-controller="Clubs" asp-action="Index">@Localizer["Discard"]</a>
    </div>
</form>